CREATE TABLE [dbo].[Audit]
(
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [UserId] UNIQUEIDENTIFIER NOT NULL,
  [Action] NVARCHAR(255) NOT NULL,
  [Values] NVARCHAR(MAX) NULL,
  [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
  constraint FK_Audit_User FOREIGN KEY (UserId) REFERENCES [User](Id)
)
