CREATE TABLE [dbo].[User]
(
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [Username] NVARCHAR(255) NOT NULL,
  [Email] NVARCHAR(255) NOT NULL,
  [FirstName] NVARCHAR(255) NOT NULL,
  [LastName] NVARCHAR(255) NOT NULL,
  [Password] NVARCHAR(255) NOT NULL,
  [FailedLoginAttempts] INT NOT NULL DEFAULT 0,
  [LockedUntil] DATETIME NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
  [UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE()
)
